# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LordRust
brief-intro: Vetenskapsman
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lordrust.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: LordRust73
facebook_username: jonas.t.bjorkman
github_username:  LordRust
email: lordrust@cloud8.se
weibo_username:
zhihu_username:
linkedIn_username: 
dribbble_username:

description_footer: "...Som en guldtacka lindad i citron..."

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname:
disqus_shortname: lordrust

# statistic analysis Statistical code
# Baidu statistics id，Replace the stats code with your own Baidu stats id
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
# baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: UA-96650011-3 # google analytical tracking id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
